name: SimulaHS
version: 0.0.0
synopsis: Haskell/C++ implementation of simula_cpp
author: David Kraeutmann <kane@kane.cx>

default-extensions:
  - GADTs
  - ConstraintKinds
  - KindSignatures
  - StandaloneDeriving
  - FlexibleInstances
  - FlexibleContexts
  - MultiParamTypeClasses
  - FunctionalDependencies
  - ScopedTypeVariables
  - RankNTypes
  - RecursiveDo
  - DefaultSignatures
  - PatternSynonyms
  - LambdaCase
  - ForeignFunctionInterface
  - QuasiQuotes
  - TemplateHaskell

dependencies:
  - base >= 4.9 && < 5
  - bytestring
  - containers
  - file-embed
  - inline-c
  - inline-c-cpp
  - lens
  - linear
  - linear-opengl
  - monad-loops
  - mtl
  - OpenGL
  - OpenGLRaw
  - primitive
  - template-haskell
  - transformers
  - vector
  - StateVar

_cpp_options: &cpp_options
  include-dirs:
    - simula_cpp/src/protocol
    - simula_cpp/src/compositor
    - simula_cpp/src/device

# hack: library won't link with this
#  extra-lib-dirs:
#    - simula_cpp/lib

  ghc-options:
    - -pgmlg++
            
  cc-options:
# hack: see above
    - -Lsimula_cpp/lib
    - -fPIC
    - -std=c++11

  ld-options:
    - -Lsimula_cpp/lib
    
_executable_options: &executable_options
  dependencies: [base, SimulaHS]
    
library:
  <<: *cpp_options
  source-dirs: src
  c-sources: src/**/*.cpp
  exposed-modules:
    - Simula.Compositor
    - Simula.Compositor.Types
    - Simula.Context
    - Simula.Utils

executables:
  simple-compositor:
    <<: *cpp_options
    <<: *executable_options
    buildable: false

    extra-libraries:
      - stdc++
      - motorcar-compositor

    
    main: SimpleCompositor.hs
    source-dirs: app
    c-sources: app/SimpleCompositor.cpp
    

  osvr-compositor:
    <<: *cpp_options
    <<: *executable_options

    buildable: false

    extra-libraries:
      - stdc++
      - motorcar-compositor
      - osvrClientKit
      - osvrRenderManager
    
    main: OsvrCompositor.hs
    source-dirs: app
    c-sources:
      - app/OsvrCompositor.cpp
      - simula_cpp/src/device/osvr_hmd.cpp
      - simula_cpp/src/device/osvr_controller.cpp

  
