name: SimulaHS
version: 0.0.0
synopsis: Haskell/C++ implementation of simula_cpp
author: David Kraeutmann <kane@kane.cx>

default-extensions:
  - ForeignFunctionInterface
  - QuasiQuotes
  - TemplateHaskell

dependencies:
  - base >= 4.9 && < 5
  - containers
  - inline-c
  - inline-c-cpp
  - vector

_cpp_options: &cpp_options
  include-dirs:
    - simula_cpp/src/protocol
    - simula_cpp/src/compositor
    - simula_cpp/src/device
    
  extra-lib-dirs:
    - simula_cpp/lib

  ghc-options:
    - -pgmlg++
            
  cc-options:
    - -fPIC
    - -std=c++11

_executable_options: &executable_options
  dependencies: [base, SimulaHS]
    
library:
  <<: *cpp_options
  source-dirs: src
  exposed-modules:
    - Simula.Compositor
    - Simula.Context
    - Simula.Utils

executables:
  simple-compositor:
    <<: *cpp_options
    <<: *executable_options

    extra-libraries:
      - stdc++
      - motorcar-compositor

    
    main: SimpleCompositor.hs
    source-dirs: app
    c-sources: app/SimpleCompositor.cpp
    

  osvr-compositor:
    <<: *cpp_options
    <<: *executable_options

    extra-libraries:
      - stdc++
      - motorcar-compositor
      - osvrClientKit
      - osvrRenderManager
    
    main: OsvrCompositor.hs
    source-dirs: app
    c-sources:
      - app/OsvrCompositor.cpp
      - simula_cpp/src/device/osvr_hmd.cpp
      - simula_cpp/src/device/osvr_controller.cpp

  
