name: simula-wayland
version: 0.0.0
synopsis: Haskell bindings for Wayland
author: David Kraeutmann <kane@kane.cx>
build-tools: 
  - c2hs

default-extensions:
  - GADTs
  - ConstraintKinds
  - KindSignatures
  - StandaloneDeriving
  - FlexibleInstances
  - FlexibleContexts
  - MultiParamTypeClasses
  - FunctionalDependencies
  - ScopedTypeVariables
  - RankNTypes
  - RecursiveDo
  - DefaultSignatures
  - PatternSynonyms
  - LambdaCase
  - ForeignFunctionInterface
  - QuasiQuotes
  - TemplateHaskell
  - OverloadedStrings

dependencies:
  - base >= 4.9 && < 5
  - containers
  - inline-c



library:
  extra-libraries:
    - wayland-server
  source-dirs: src
  c-sources: cbits/*.c
  include-dirs: cbits

  exposed-modules:
    - Simula.WaylandServer
    - Simula.MotorcarServer

